// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBlogPostFields {
  /** Internal Name */
  internalName: string;

  /** Title */
  title?: string | undefined;

  /** Excerpt */
  excerpt: string;

  /** Content */
  content?: Document | undefined;
}

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomepageFields {
  /** Internal Name */
  internalName: string;

  /** Logo */
  logo?: Asset | undefined;

  /** Title */
  title: string;

  /** Teaser blog */
  teaserBlog2?: IBlogPost[] | undefined;
}

export interface IHomepage extends Entry<IHomepageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homepage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITextWithColorFields {
  /** Internal Name */
  internalName: string;

  /** Text */
  text: string;

  /** Color */
  color?: Record<string, any> | undefined;
}

export interface ITextWithColor extends Entry<ITextWithColorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "textWithColor";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "blogPost" | "homepage" | "textWithColor";

export type IEntry = IBlogPost | IHomepage | ITextWithColor;

export type LOCALE_CODE = "en" | "fr";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en";
